// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Prestigelisten.Persistence;

#nullable disable

namespace Prestigelisten.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251101103325_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Prestigelisten.Core.Models.Calendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer")
                        .HasColumnName("race_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_calendar");

                    b.HasIndex("RaceId")
                        .HasDatabaseName("ix_calendar_race_id");

                    b.ToTable("calendar", (string)null);
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Credit")
                        .HasColumnType("text")
                        .HasColumnName("credit");

                    b.Property<string>("CreditUrl")
                        .HasColumnType("text")
                        .HasColumnName("credit_url");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.HasKey("Id")
                        .HasName("pk_images");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.MetaRace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .HasColumnType("text")
                        .HasColumnName("color_hex");

                    b.Property<bool>("DarkText")
                        .HasColumnType("boolean")
                        .HasColumnName("dark_text");

                    b.Property<int?>("ImageId")
                        .HasColumnType("integer")
                        .HasColumnName("image_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("NationId")
                        .HasColumnType("integer")
                        .HasColumnName("nation_id");

                    b.HasKey("Id")
                        .HasName("pk_meta_races");

                    b.HasIndex("ImageId")
                        .HasDatabaseName("ix_meta_races_image_id");

                    b.HasIndex("NationId")
                        .HasDatabaseName("ix_meta_races_nation_id");

                    b.ToTable("meta_races", (string)null);
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.Nation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<int>("ActivePoints")
                        .HasColumnType("integer")
                        .HasColumnName("active_points");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.HasKey("Id")
                        .HasName("pk_nations");

                    b.ToTable("nations", (string)null);
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.NationSeason", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("PointsAllTime")
                        .HasColumnType("integer")
                        .HasColumnName("points_all_time");

                    b.Property<int?>("PointsForYear")
                        .HasColumnType("integer")
                        .HasColumnName("points_for_year");

                    b.Property<int>("RankAllTime")
                        .HasColumnType("integer")
                        .HasColumnName("rank_all_time");

                    b.Property<int?>("RankForYear")
                        .HasColumnType("integer")
                        .HasColumnName("rank_for_year");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_nation_seasons");

                    b.ToTable("nation_seasons", (string)null);
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.PointSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int>("RaceClassId")
                        .HasColumnType("integer")
                        .HasColumnName("race_class_id");

                    b.Property<int>("ResultType")
                        .HasColumnType("integer")
                        .HasColumnName("result_type");

                    b.HasKey("Id")
                        .HasName("pk_point_system");

                    b.HasIndex("RaceClassId")
                        .HasDatabaseName("ix_point_system_race_class_id");

                    b.ToTable("point_system", (string)null);
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.PreviousNationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer")
                        .HasColumnName("end_year");

                    b.Property<int>("NationId")
                        .HasColumnType("integer")
                        .HasColumnName("nation_id");

                    b.Property<int>("RiderId")
                        .HasColumnType("integer")
                        .HasColumnName("rider_id");

                    b.Property<int?>("StartYear")
                        .HasColumnType("integer")
                        .HasColumnName("start_year");

                    b.HasKey("Id")
                        .HasName("pk_previous_nationalities");

                    b.HasIndex("NationId")
                        .HasDatabaseName("ix_previous_nationalities_nation_id");

                    b.HasIndex("RiderId")
                        .HasDatabaseName("ix_previous_nationalities_rider_id");

                    b.ToTable("previous_nationalities", (string)null);
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("ActiveSpanString")
                        .HasColumnType("text")
                        .HasColumnName("active_span_string");

                    b.Property<int>("MetaRaceId")
                        .HasColumnType("integer")
                        .HasColumnName("meta_race_id");

                    b.Property<int>("RaceClassId")
                        .HasColumnType("integer")
                        .HasColumnName("race_class_id");

                    b.HasKey("Id")
                        .HasName("pk_races");

                    b.HasIndex("MetaRaceId")
                        .HasDatabaseName("ix_races_meta_race_id");

                    b.HasIndex("RaceClassId")
                        .HasDatabaseName("ix_races_race_class_id");

                    b.ToTable("races", (string)null);
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.RaceClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortingIndex")
                        .HasColumnType("integer")
                        .HasColumnName("sorting_index");

                    b.HasKey("Id")
                        .HasName("pk_race_classes");

                    b.ToTable("race_classes", (string)null);
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.RaceDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer")
                        .HasColumnName("race_id");

                    b.Property<int?>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.HasKey("Id")
                        .HasName("pk_race_dates");

                    b.HasIndex("RaceId")
                        .HasDatabaseName("ix_race_dates_race_id");

                    b.ToTable("race_dates", (string)null);
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("NationSeasonId")
                        .HasColumnType("bigint")
                        .HasColumnName("nation_season_id");

                    b.Property<int?>("Placement")
                        .HasColumnType("integer")
                        .HasColumnName("placement");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer")
                        .HasColumnName("race_id");

                    b.Property<int>("ResultType")
                        .HasColumnType("integer")
                        .HasColumnName("result_type");

                    b.Property<int>("RiderId")
                        .HasColumnType("integer")
                        .HasColumnName("rider_id");

                    b.Property<long>("RiderSeasonId")
                        .HasColumnType("bigint")
                        .HasColumnName("rider_season_id");

                    b.Property<int>("SheetIndex")
                        .HasColumnType("integer")
                        .HasColumnName("sheet_index");

                    b.Property<int?>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_results");

                    b.HasIndex("NationSeasonId")
                        .HasDatabaseName("ix_results_nation_season_id");

                    b.HasIndex("RaceId")
                        .HasDatabaseName("ix_results_race_id");

                    b.HasIndex("RiderId")
                        .HasDatabaseName("ix_results_rider_id");

                    b.HasIndex("RiderSeasonId")
                        .HasDatabaseName("ix_results_rider_season_id");

                    b.ToTable("results", (string)null);
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.Rider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int?>("ImageId")
                        .HasColumnType("integer")
                        .HasColumnName("image_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<int>("NationId")
                        .HasColumnType("integer")
                        .HasColumnName("nation_id");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_riders");

                    b.HasIndex("ImageId")
                        .HasDatabaseName("ix_riders_image_id");

                    b.HasIndex("NationId")
                        .HasDatabaseName("ix_riders_nation_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_riders_team_id");

                    b.ToTable("riders", (string)null);
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.RiderSeason", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("PointsAllTime")
                        .HasColumnType("integer")
                        .HasColumnName("points_all_time");

                    b.Property<int?>("PointsForYear")
                        .HasColumnType("integer")
                        .HasColumnName("points_for_year");

                    b.Property<int>("RankAllTime")
                        .HasColumnType("integer")
                        .HasColumnName("rank_all_time");

                    b.Property<int?>("RankForYear")
                        .HasColumnType("integer")
                        .HasColumnName("rank_for_year");

                    b.Property<int>("RiderId")
                        .HasColumnType("integer")
                        .HasColumnName("rider_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_rider_seasons");

                    b.HasIndex("RiderId")
                        .HasDatabaseName("ix_rider_seasons_rider_id");

                    b.ToTable("rider_seasons", (string)null);
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("NationId")
                        .HasColumnType("integer")
                        .HasColumnName("nation_id");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("NationId")
                        .HasDatabaseName("ix_teams_nation_id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.Calendar", b =>
                {
                    b.HasOne("Prestigelisten.Core.Models.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_races_race_id");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.MetaRace", b =>
                {
                    b.HasOne("Prestigelisten.Core.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .HasConstraintName("fk_meta_races_images_image_id");

                    b.HasOne("Prestigelisten.Core.Models.Nation", "Nation")
                        .WithMany()
                        .HasForeignKey("NationId")
                        .HasConstraintName("fk_meta_races_nations_nation_id");

                    b.Navigation("Image");

                    b.Navigation("Nation");
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.PointSystem", b =>
                {
                    b.HasOne("Prestigelisten.Core.Models.RaceClass", "RaceClass")
                        .WithMany()
                        .HasForeignKey("RaceClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_point_system_race_classes_race_class_id");

                    b.Navigation("RaceClass");
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.PreviousNationality", b =>
                {
                    b.HasOne("Prestigelisten.Core.Models.Nation", "Nation")
                        .WithMany()
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_previous_nationalities_nations_nation_id");

                    b.HasOne("Prestigelisten.Core.Models.Rider", "Rider")
                        .WithMany()
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_previous_nationalities_riders_rider_id");

                    b.Navigation("Nation");

                    b.Navigation("Rider");
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.Race", b =>
                {
                    b.HasOne("Prestigelisten.Core.Models.MetaRace", "MetaRace")
                        .WithMany()
                        .HasForeignKey("MetaRaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_races_meta_races_meta_race_id");

                    b.HasOne("Prestigelisten.Core.Models.RaceClass", "RaceClass")
                        .WithMany()
                        .HasForeignKey("RaceClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_races_race_classes_race_class_id");

                    b.Navigation("MetaRace");

                    b.Navigation("RaceClass");
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.RaceDate", b =>
                {
                    b.HasOne("Prestigelisten.Core.Models.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_race_dates_races_race_id");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.Result", b =>
                {
                    b.HasOne("Prestigelisten.Core.Models.NationSeason", "NationSeason")
                        .WithMany()
                        .HasForeignKey("NationSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_results_nation_seasons_nation_season_id");

                    b.HasOne("Prestigelisten.Core.Models.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_results_races_race_id");

                    b.HasOne("Prestigelisten.Core.Models.Rider", "Rider")
                        .WithMany()
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_results_riders_rider_id");

                    b.HasOne("Prestigelisten.Core.Models.RiderSeason", "RiderSeason")
                        .WithMany()
                        .HasForeignKey("RiderSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_results_rider_seasons_rider_season_id");

                    b.Navigation("NationSeason");

                    b.Navigation("Race");

                    b.Navigation("Rider");

                    b.Navigation("RiderSeason");
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.Rider", b =>
                {
                    b.HasOne("Prestigelisten.Core.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .HasConstraintName("fk_riders_images_image_id");

                    b.HasOne("Prestigelisten.Core.Models.Nation", "Nation")
                        .WithMany()
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riders_nations_nation_id");

                    b.HasOne("Prestigelisten.Core.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .HasConstraintName("fk_riders_teams_team_id");

                    b.Navigation("Image");

                    b.Navigation("Nation");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.RiderSeason", b =>
                {
                    b.HasOne("Prestigelisten.Core.Models.Rider", "Rider")
                        .WithMany()
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rider_seasons_riders_rider_id");

                    b.Navigation("Rider");
                });

            modelBuilder.Entity("Prestigelisten.Core.Models.Team", b =>
                {
                    b.HasOne("Prestigelisten.Core.Models.Nation", "Nation")
                        .WithMany()
                        .HasForeignKey("NationId")
                        .HasConstraintName("fk_teams_nations_nation_id");

                    b.Navigation("Nation");
                });
#pragma warning restore 612, 618
        }
    }
}
