export const urls: Record<string, string> = {
    home: "/",
    year: "/year",
    team: "/team",
    calendar: "/calendar",
    race: "/race",
    list: "/list",
    listRiders: "/list/riders",
    listNations: "/list/nations",
    listRiders3YearPeriod: "/list/riders/3-year_period",
    listRidersAges: "/list/riders/ages",
    listRidersGreatestSeasons: "/list/riders/greatest_seasons",
    nation: "/nation",
    about: "/about_prestigelisten",
    resultsThisYear: "/results_this_year",
    pointSystem: "/point_system",
    rider: "/rider",
    compare: "/compare",
    compareRiders: "/compare/riders",
    compareNations: "/compare/nations",
}