import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: { lang: "en" | "da" };
}>) {
  const messages = await getMessages();
  const { lang } = await params;

  return (
    <html lang={lang}>
      <NextIntlClientProvider messages={messages}>
        <body
            className={`${inter.variable} antialiased overflow-x-hidden text-sm sm:text-base flex flex-col min-h-screen`}
        >
          {children}
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
