import type { Metadata } from "next";
import "./globals.css";
import "../../../node_modules/flag-icons/css/flag-icons.min.css";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import Header from "@/components/layout/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: "en" | "da" }>;
}>) {
  const messages = await getMessages();
  const { lang } = await params;

  return (
    <html lang={lang}>
      <NextIntlClientProvider messages={messages}>
        <body
            className={`font-inter antialiased overflow-x-hidden text-sm sm:text-[0.938rem] flex flex-col min-h-screen`}
        >
          <Header/>
          <div className="pt-11 sm:pt-[3.25rem]">
            {children}
          </div>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
