using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Prestigelisten.Core.Models;

namespace Prestigelisten.Persistence.Configurations;

public class MetaRacesConfiguration : IEntityTypeConfiguration<MetaRace>
{
    public void Configure(EntityTypeBuilder<MetaRace> builder)
    {
        builder.HasData(GetSeedData());
    }

    private static IEnumerable<object> GetSeedData()
    {
        return 
        [
            new { Id = 1, Name = "Tour de France", ColorHex = "#ffff00", NationId = 3, DarkText = true },
            new { Id = 2, Name = "Vuelta a España", ColorHex = "#da291c", NationId = 4, DarkText = false },
            new { Id = 3, Name = "Giro d'Italia", ColorHex = "#FF276E", NationId = 1, DarkText = false },
            new { Id = 4, Name = "Ronde van Vlaanderen", ColorHex = "#fce201", NationId = 2, DarkText = true },
            new { Id = 5, Name = "Paris-Roubaix", ColorHex = "#ff0000", NationId = 3, DarkText = false },
            new { Id = 7, Name = "Milano-Sanremo", ColorHex = "#ff7b4d", NationId = 1, DarkText = false },
            new { Id = 8, Name = "Il Lombardia", ColorHex = "#12b362", NationId = 1, DarkText = false },
            new { Id = 9, Name = "Paris-Tours", ColorHex = "#009790", NationId = 3, DarkText = false },
            new { Id = 11, Name = "Grand Prix Wolber", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 12, Name = "Cuca Cocoa Cup", ColorHex = (string?)null, NationId = 8, DarkText = false },
            new { Id = 14, Name = "Bol d'Or", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 15, Name = "Paris-Brest-Paris", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 16, Name = "Tirreno-Adriatico", ColorHex = "#003866", NationId = 1, DarkText = false },
            new { Id = 17, Name = "Tour de Romandie", ColorHex = "#e30c13", NationId = 6, DarkText = false },
            new { Id = 18, Name = "Paris-Nice", ColorHex = "#0092cf", NationId = 3, DarkText = false },
            new { Id = 19, Name = "Tour de Suisse", ColorHex = "#a61c2a", NationId = 6, DarkText = false },
            new { Id = 20, Name = "Criterium du Dauphiné", ColorHex = "#d64c13", NationId = 3, DarkText = false },
            new { Id = 21, Name = "Itzulia Basque Country", ColorHex = "#be2423", NationId = 4, DarkText = false },
            new { Id = 22, Name = "Volta Ciclista a Catalunya", ColorHex = "#ce122b", NationId = 4, DarkText = false },
            new { Id = 23, Name = "La Course du Tour de France", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 24, Name = "Gent-Wevelgem", ColorHex = "#e94f35", NationId = 2, DarkText = false },
            new { Id = 25, Name = "Fleche Wallonne", ColorHex = "#ac9d6e", NationId = 2, DarkText = false },
            new { Id = 26, Name = "Strade Bianche", ColorHex = "#b0354a", NationId = 1, DarkText = false },
            new { Id = 28, Name = "Amstel Gold Race", ColorHex = "#407900", NationId = 5, DarkText = false },
            new { Id = 29, Name = "Liège-Bastogne-Liège", ColorHex = "#00491f", NationId = 2, DarkText = false },
            new { Id = 32, Name = "Berlin-Cottbus-Berlin", ColorHex = (string?)null, NationId = 7, DarkText = false },
            new { Id = 33, Name = "Gran Fondo - La Seicento", ColorHex = (string?)null, NationId = 1, DarkText = false },
            new { Id = 34, Name = "Lyon-Paris-Lyon", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 35, Name = "Circuit de Paris", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 36, Name = "Bordeaux-Paris-Bordeaux", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 38, Name = "Roma-Napoli-Roma", ColorHex = (string?)null, NationId = 1, DarkText = false },
            new { Id = 42, Name = "Tour de Pologne", ColorHex = "#2c2c2c", NationId = 20, DarkText = false },
            new { Id = 45, Name = "Giro di Sicilia", ColorHex = (string?)null, NationId = 1, DarkText = false },
            new { Id = 46, Name = "Paris - Saint-Etienne", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 47, Name = "Circuit des Champs de Bataille", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 48, Name = "Circuit de France", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 49, Name = "Völkerschlacht-Jubiläumsfahrt", ColorHex = (string?)null, NationId = 7, DarkText = false },
            new { Id = 50, Name = "Ronde de France", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 53, Name = "Dwars door Vlaanderen", ColorHex = "#61c3d9", NationId = 2, DarkText = true },
            new { Id = 54, Name = "BEMER Cyclassics", ColorHex = "#011e41", NationId = 7, DarkText = false },
            new { Id = 55, Name = "E3 Saxo Classic", ColorHex = "#237AEB", NationId = 2, DarkText = false },
            new { Id = 58, Name = "Grand Prix des Nations", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 59, Name = "North Road 100", ColorHex = (string?)null, NationId = 8, DarkText = false },
            new { Id = 60, Name = "Paris-Spa", ColorHex = (string?)null, NationId = 2, DarkText = false },
            new { Id = 61, Name = "Marseille-Paris", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 62, Name = "Rund um Berlin", ColorHex = (string?)null, NationId = 7, DarkText = false },
            new { Id = 63, Name = "Paris-Rennes", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 64, Name = "Wien-Graz-Triest", ColorHex = (string?)null, NationId = 24, DarkText = false },
            new { Id = 65, Name = "Paris-Nantes-Paris", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 66, Name = "Tour of the Alps", ColorHex = "#407900", NationId = 1, DarkText = false },
            new { Id = 67, Name = "Tour of Guangxi", ColorHex = "#e4362d", NationId = 52, DarkText = false },
            new { Id = 72, Name = "UAE Tour", ColorHex = "#E73743", NationId = 51, DarkText = false },
            new { Id = 73, Name = "Renewi Tour", ColorHex = "#78BE20", NationId = 2, DarkText = false },
            new { Id = 74, Name = "G.P. Sporting", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 77, Name = "Tour du Sud-Est", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 78, Name = "Tour of Beijing", ColorHex = (string?)null, NationId = 52, DarkText = false },
            new { Id = 79, Name = "Deutschland Tour", ColorHex = "#e01021", NationId = 7, DarkText = false },
            new { Id = 83, Name = "Paris-Luxembourg", ColorHex = (string?)null, NationId = 11, DarkText = false },
            new { Id = 84, Name = "Presidential Cycling Tour of Turkey", ColorHex = (string?)null, NationId = 53, DarkText = false },
            new { Id = 86, Name = "Bretagne Classic - Ouest-France", ColorHex = "#ffff00", NationId = 3, DarkText = true },
            new { Id = 87, Name = "Grand Prix Cycliste de Quebec", ColorHex = "#cbdb2a", NationId = 26, DarkText = true },
            new { Id = 88, Name = "Eschborn-Frankfurt", ColorHex = "#e01021", NationId = 7, DarkText = false },
            new { Id = 89, Name = "Grand Prix Cycliste de Montreal", ColorHex = "#ccd93e", NationId = 26, DarkText = true },
            new { Id = 90, Name = "Cadel Evans Great Ocean Road Race", ColorHex = "#00b1ff", NationId = 10, DarkText = false },
            new { Id = 91, Name = "Milano-Torino", ColorHex = "#ff4050", NationId = 1, DarkText = false },
            new { Id = 94, Name = "Donostia San Sebastian Klasikoa", ColorHex = "#00A8E7", NationId = 4, DarkText = false },
            new { Id = 97, Name = "G.P. Stan Ockers", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 98, Name = "Grand Prix de Lunel", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 99, Name = "Grand Prix des Amériques", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 101, Name = "Marseille-Lyon", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 102, Name = "Milano-Modena", ColorHex = (string?)null, NationId = 1, DarkText = false },
            new { Id = 103, Name = "Nord-West Schweizer Rundfahrt", ColorHex = (string?)null, NationId = 6, DarkText = false },
            new { Id = 104, Name = "Paris-Menin", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 105, Name = "Bordeaux-Paris", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 106, Name = "Giro di Romagna", ColorHex = (string?)null, NationId = 1, DarkText = false },
            new { Id = 107, Name = "Wien-Berlin", ColorHex = (string?)null, NationId = 7, DarkText = false },
            new { Id = 108, Name = "Wincanton Classic", ColorHex = (string?)null, NationId = 8, DarkText = false },
            new { Id = 109, Name = "Zürich-München", ColorHex = (string?)null, NationId = 7, DarkText = false },
            new { Id = 111, Name = "Rund um Spessart und Rhön", ColorHex = (string?)null, NationId = 7, DarkText = false },
            new { Id = 113, Name = "Gran Piemonte", ColorHex = "#e32d33", NationId = 1, DarkText = false },
            new { Id = 114, Name = "Genoa-Nice", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 115, Name = "Volta a la Communitat Valenciana", ColorHex = "#3b8ced", NationId = 4, DarkText = false },
            new { Id = 116, Name = "Baloise Belgium Tour", ColorHex = "#000D6E", NationId = 2, DarkText = false },
            new { Id = 118, Name = "Tour of Britain", ColorHex = "#003b6f", NationId = 8, DarkText = false },
            new { Id = 119, Name = "4 Jours de Dunkerque", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 120, Name = "Tour Down Under", ColorHex = "#ff671d", NationId = 10, DarkText = false },
            new { Id = 124, Name = "Criterium International", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 125, Name = "Giro del Lazio", ColorHex = (string?)null, NationId = 1, DarkText = false },
            new { Id = 128, Name = "Tour de l'Avenir", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 129, Name = "Tour of California", ColorHex = (string?)null, NationId = 9, DarkText = false },
            new { Id = 130, Name = "Tour de l'Ouest", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 133, Name = "Setmana-Catalana", ColorHex = (string?)null, NationId = 4, DarkText = false },
            new { Id = 134, Name = "GP du Midi-Libre", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 135, Name = "Kuurne-Bruxelles-Kuurne", ColorHex = "#b91817", NationId = 2, DarkText = false },
            new { Id = 137, Name = "Scheldeprijs", ColorHex = "#afca0b", NationId = 2, DarkText = true },
            new { Id = 138, Name = "Brabantse Pijl", ColorHex = "#c10b25", NationId = 2, DarkText = false },
            new { Id = 140, Name = "Brussels Cycling Classic", ColorHex = "#8ccaae", NationId = 2, DarkText = true },
            new { Id = 141, Name = "Giro dell'Emilia", ColorHex = (string?)null, NationId = 1, DarkText = false },
            new { Id = 142, Name = "Tre Valli Varesine", ColorHex = "#e30613", NationId = 1, DarkText = false },
            new { Id = 145, Name = "Classic Brugge-De Panne", ColorHex = "#f37822", NationId = 2, DarkText = false },
            new { Id = 147, Name = "Omloop Het Nieuwsblad", ColorHex = "#242857", NationId = 2, DarkText = false },
            new { Id = 155, Name = "Grosser Sachsenpreis", ColorHex = (string?)null, NationId = 7, DarkText = false },
            new { Id = 156, Name = "Japan Cup Cycle Road Race", ColorHex = (string?)null, NationId = 47, DarkText = false },
            new { Id = 158, Name = "Circuit de Belgique", ColorHex = (string?)null, NationId = 2, DarkText = false },
            new { Id = 159, Name = "Paris-Clermont-Ferrand", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 162, Name = "Prudential RideLondon-Surrey Classic", ColorHex = (string?)null, NationId = 8, DarkText = false },
            new { Id = 163, Name = "Züri-Metzgete", ColorHex = (string?)null, NationId = 6, DarkText = false },
            new { Id = 164, Name = "North Road 24 Hour Road Race", ColorHex = (string?)null, NationId = 8, DarkText = false },
            new { Id = 168, Name = "Fransk mester", ColorHex = "#0055A4", NationId = 3, DarkText = false },
            new { Id = 169, Name = "Spansk mester", ColorHex = "#EF3340", NationId = 4, DarkText = false },
            new { Id = 170, Name = "Belgisk mester", ColorHex = "#0098d4", NationId = 2, DarkText = false },
            new { Id = 171, Name = "Nederlandsk mester", ColorHex = "#F36C21", NationId = 5, DarkText = false },
            new { Id = 172, Name = "Italiensk mester", ColorHex = "#0A36AF", NationId = 1, DarkText = false },
            new { Id = 173, Name = "Spansk mester i enkeltstart", ColorHex = "#EF3340", NationId = 4, DarkText = false },
            new { Id = 174, Name = "Fransk mester i enkeltstart", ColorHex = "#0055A4", NationId = 3, DarkText = false },
            new { Id = 175, Name = "Belgisk mester i enkeltstart", ColorHex = "#0098d4", NationId = 2, DarkText = false },
            new { Id = 176, Name = "Italiensk mester i enkeltstart", ColorHex = "#0A36AF", NationId = 1, DarkText = false },
            new { Id = 177, Name = "Nederlandsk mester i enkeltstart", ColorHex = "#F36C21", NationId = 5, DarkText = false },
            new { Id = 178, Name = "Colombiansk mester", ColorHex = "#003087", NationId = 12, DarkText = false },
            new { Id = 179, Name = "Ecuadoriansk mester", ColorHex = "#FFD100", NationId = 27, DarkText = false },
            new { Id = 180, Name = "Australsk mester", ColorHex = "#6dbd45", NationId = 10, DarkText = false },
            new { Id = 181, Name = "Tysk mester", ColorHex = "#2c2c2c", NationId = 7, DarkText = false },
            new { Id = 182, Name = "Norsk mester", ColorHex = "#BA0C2F", NationId = 17, DarkText = false },
            new { Id = 183, Name = "Amerikansk mester", ColorHex = "#B22234", NationId = 9, DarkText = false },
            new { Id = 184, Name = "Portugisisk mester", ColorHex = "#DA291C", NationId = 19, DarkText = false },
            new { Id = 185, Name = "Schweizisk mester", ColorHex = "#DA291C", NationId = 6, DarkText = false },
            new { Id = 186, Name = "Slovensk mester", ColorHex = "#C7EA46", NationId = 15, DarkText = false },
            new { Id = 187, Name = "Tjekkisk mester", ColorHex = "#E40046", NationId = 25, DarkText = false },
            new { Id = 188, Name = "Dansk mester", ColorHex = "#DA291C", NationId = 14, DarkText = false },
            new { Id = 189, Name = "Østrigsk mester", ColorHex = "#ed2939", NationId = 24, DarkText = false },
            new { Id = 190, Name = "Britisk mester", ColorHex = "#012169", NationId = 8, DarkText = false },
            new { Id = 191, Name = "Irsk mester", ColorHex = (string?)null, NationId = 13, DarkText = false },
            new { Id = 192, Name = "Canadisk mester", ColorHex = (string?)null, NationId = 26, DarkText = false },
            new { Id = 193, Name = "Belarusisk mester", ColorHex = (string?)null, NationId = 35, DarkText = false },
            new { Id = 194, Name = "Kasakhisk mester", ColorHex = (string?)null, NationId = 21, DarkText = false },
            new { Id = 195, Name = "Litauisk mester", ColorHex = (string?)null, NationId = 31, DarkText = false },
            new { Id = 196, Name = "Russisk mester", ColorHex = (string?)null, NationId = 16, DarkText = false },
            new { Id = 197, Name = "Svensk mester", ColorHex = (string?)null, NationId = 22, DarkText = false },
            new { Id = 198, Name = "Polsk mester", ColorHex = (string?)null, NationId = 20, DarkText = false },
            new { Id = 199, Name = "Ukrainsk mester", ColorHex = (string?)null, NationId = 23, DarkText = false },
            new { Id = 200, Name = "Luxembourgsk mester", ColorHex = (string?)null, NationId = 11, DarkText = false },
            new { Id = 201, Name = "Colombiansk mester i enkeltstart", ColorHex = "#003087", NationId = 12, DarkText = false },
            new { Id = 202, Name = "Ecuadoriansk mester i enkeltstart", ColorHex = "#FFD100", NationId = 27, DarkText = false },
            new { Id = 203, Name = "Norsk mester i enkeltstart", ColorHex = "#BA0C2F", NationId = 17, DarkText = false },
            new { Id = 204, Name = "Australsk mester i enkeltstart", ColorHex = "#6dbd45", NationId = 10, DarkText = false },
            new { Id = 205, Name = "Schweizisk mester i enkeltstart", ColorHex = "#DA291C", NationId = 6, DarkText = false },
            new { Id = 206, Name = "Tjekkisk mester i enkeltstart", ColorHex = "#E40046", NationId = 25, DarkText = false },
            new { Id = 207, Name = "Tysk mester i enkeltstart", ColorHex = "#2c2c2c", NationId = 7, DarkText = false },
            new { Id = 208, Name = "Dansk mester i enkeltstart", ColorHex = "#DA291C", NationId = 14, DarkText = false },
            new { Id = 209, Name = "Slovensk mester i enkeltstart", ColorHex = "#C7EA46", NationId = 15, DarkText = false },
            new { Id = 210, Name = "Portugisisk mester i enkeltstart", ColorHex = "#DA291C", NationId = 19, DarkText = false },
            new { Id = 211, Name = "Østrigsk mester i enkeltstart", ColorHex = "#ed2939", NationId = 24, DarkText = false },
            new { Id = 212, Name = "Amerikansk mester i enkeltstart", ColorHex = "#B22234", NationId = 9, DarkText = false },
            new { Id = 213, Name = "Britisk mester i enkeltstart", ColorHex = "#012169", NationId = 8, DarkText = false },
            new { Id = 214, Name = "Litauisk mester i enkeltstart", ColorHex = (string?)null, NationId = 31, DarkText = false },
            new { Id = 215, Name = "Polsk mester i enkeltstart", ColorHex = (string?)null, NationId = 20, DarkText = false },
            new { Id = 216, Name = "Russisk mester i enkeltstart", ColorHex = (string?)null, NationId = 16, DarkText = false },
            new { Id = 217, Name = "Ukrainsk mester i enkeltstart", ColorHex = (string?)null, NationId = 23, DarkText = false },
            new { Id = 218, Name = "Belarusisk mester i enkeltstart", ColorHex = (string?)null, NationId = 35, DarkText = false },
            new { Id = 219, Name = "Luxembourgsk mester i enkeltstart", ColorHex = (string?)null, NationId = 11, DarkText = false },
            new { Id = 220, Name = "Canadisk mester i enkeltstart", ColorHex = (string?)null, NationId = 26, DarkText = false },
            new { Id = 221, Name = "Kasakhisk mester i enkeltstart", ColorHex = (string?)null, NationId = 21, DarkText = false },
            new { Id = 222, Name = "Svensk mester i enkeltstart", ColorHex = (string?)null, NationId = 22, DarkText = false },
            new { Id = 223, Name = "Irsk mester i enkeltstart", ColorHex = (string?)null, NationId = 13, DarkText = false },
            new { Id = 225, Name = "OL i enkeltstart", ColorHex = (string?)null, NationId = (int?)null, DarkText = false },
            new { Id = 226, Name = "OL 12 timers løb", ColorHex = (string?)null, NationId = (int?)null, DarkText = false },
            new { Id = 227, Name = "VM i linjeløb", ColorHex = "#ededed", NationId = (int?)null, DarkText = true },
            new { Id = 228, Name = "VM i enkeltstart", ColorHex = "#ededed", NationId = (int?)null, DarkText = true },
            new { Id = 229, Name = "EM i linjeløb", ColorHex = "#004494", NationId = (int?)null, DarkText = false },
            new { Id = 230, Name = "EM i enkeltstart", ColorHex = "#004494", NationId = (int?)null, DarkText = false },
            new { Id = 231, Name = "OL i linjeløb", ColorHex = (string?)null, NationId = (int?)null, DarkText = false },
            new { Id = 233, Name = "Trofeo Baracchi", ColorHex = "#02B3E4", NationId = 1, DarkText = false },
            new { Id = 234, Name = "48 Hours Race North Shields", ColorHex = (string?)null, NationId = 8, DarkText = false },
            new { Id = 235, Name = "50 Miles Professional Championship", ColorHex = (string?)null, NationId = 8, DarkText = false },
            new { Id = 236, Name = "Amsterdam-Arnhem-Amsterdam", ColorHex = (string?)null, NationId = 5, DarkText = false },
            new { Id = 237, Name = "Anerley C.C. 24 hours race", ColorHex = (string?)null, NationId = 8, DarkText = false },
            new { Id = 238, Name = "Angers-Tours-Angers", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 239, Name = "Berlin-Hamburg", ColorHex = (string?)null, NationId = 7, DarkText = false },
            new { Id = 240, Name = "Championship of Britain", ColorHex = (string?)null, NationId = 8, DarkText = false },
            new { Id = 241, Name = "Caen-Cherbourg-Caen", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 242, Name = "Clarksville 100 Mile Road Race", ColorHex = (string?)null, NationId = 9, DarkText = false },
            new { Id = 243, Name = "Classique des Alpes", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 244, Name = "Coors Classic", ColorHex = (string?)null, NationId = 9, DarkText = false },
            new { Id = 245, Name = "Copenhagen Sprint", ColorHex = "#00ab4c", NationId = 14, DarkText = false },
            new { Id = 246, Name = "Corsa delle Tre Capitali", ColorHex = (string?)null, NationId = 1, DarkText = false },
            new { Id = 247, Name = "Derby Du Nord", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 248, Name = "Facile 24 Hours Race", ColorHex = (string?)null, NationId = 8, DarkText = false },
            new { Id = 249, Name = "GP de Fourmies", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 250, Name = "Giro di Campania", ColorHex = (string?)null, NationId = 1, DarkText = false },
            new { Id = 251, Name = "Grafenstaden-St. Ludvig-Grafenstaden", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 252, Name = "Grand Course International de la Union Sportive", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 253, Name = "Krakow-Lwow", ColorHex = (string?)null, NationId = 20, DarkText = false },
            new { Id = 254, Name = "Köln-Breslau", ColorHex = (string?)null, NationId = 7, DarkText = false },
            new { Id = 255, Name = "Le Mans-Paris", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 256, Name = "London T.C. 24", ColorHex = (string?)null, NationId = 8, DarkText = false },
            new { Id = 257, Name = "Louviers-Chartres-Louviers", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 258, Name = "Lyon-Montélimar-Lyon", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 259, Name = "Maastricht-Nijmegen-Maastricht", ColorHex = (string?)null, NationId = 5, DarkText = false },
            new { Id = 260, Name = "Melbourne 24 hours", ColorHex = (string?)null, NationId = 10, DarkText = false },
            new { Id = 261, Name = "Melbourne 6x6 Hours Race", ColorHex = (string?)null, NationId = 10, DarkText = false },
            new { Id = 262, Name = "Monaco-Paris", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 263, Name = "N.C.U. 50 Championship", ColorHex = (string?)null, NationId = 8, DarkText = false },
            new { Id = 264, Name = "New York 26 Hours", ColorHex = (string?)null, NationId = 9, DarkText = false },
            new { Id = 265, Name = "Paris - Bar-le-duc", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 266, Name = "Paris - Saint-Malo", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 267, Name = "Paris-Dieppe-Paris", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 268, Name = "Paris-Dinant", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 269, Name = "Philadelphia 72 Hours Race", ColorHex = (string?)null, NationId = 9, DarkText = false },
            new { Id = 270, Name = "Quer durch Thüringen", ColorHex = (string?)null, NationId = 7, DarkText = false },
            new { Id = 271, Name = "Roma-Trieste", ColorHex = (string?)null, NationId = 1, DarkText = false },
            new { Id = 272, Name = "Rund um Mitteldeutschland", ColorHex = (string?)null, NationId = 7, DarkText = false },
            new { Id = 273, Name = "Sankt Peterburg-Moskva", ColorHex = (string?)null, NationId = 16, DarkText = false },
            new { Id = 274, Name = "Six Days Aberdeen", ColorHex = (string?)null, NationId = 8, DarkText = false },
            new { Id = 275, Name = "Six Days Boston", ColorHex = (string?)null, NationId = 9, DarkText = false },
            new { Id = 276, Name = "Six Days London", ColorHex = (string?)null, NationId = 8, DarkText = false },
            new { Id = 277, Name = "Six Days Melbourne", ColorHex = (string?)null, NationId = 10, DarkText = false },
            new { Id = 278, Name = "Six Days New York", ColorHex = (string?)null, NationId = 9, DarkText = false },
            new { Id = 279, Name = "Six Days Sydney", ColorHex = (string?)null, NationId = 10, DarkText = false },
            new { Id = 280, Name = "Springfield Professional 10", ColorHex = (string?)null, NationId = 9, DarkText = false },
            new { Id = 281, Name = "Springfield Professional 20", ColorHex = (string?)null, NationId = 9, DarkText = false },
            new { Id = 282, Name = "Stanley C.C. 24 hour road race", ColorHex = (string?)null, NationId = 9, DarkText = false },
            new { Id = 283, Name = "Sydney-Melbourne", ColorHex = (string?)null, NationId = 10, DarkText = false },
            new { Id = 284, Name = "Toulouse-Bordeaux-Toulouse", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 285, Name = "Toulouse-Béziers-Toulouse", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 286, Name = "Tour d'Europe", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 287, Name = "Tour de la Nouvelle France", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 288, Name = "Tour of Ireland", ColorHex = (string?)null, NationId = 13, DarkText = false },
            new { Id = 289, Name = "VM (amatør)", ColorHex = "#ededed", NationId = (int?)null, DarkText = false },
            new { Id = 290, Name = "Wien-Reichenberg", ColorHex = (string?)null, NationId = 24, DarkText = false },
            new { Id = 291, Name = "Zürich-Berlin", ColorHex = (string?)null, NationId = 7, DarkText = false },
            new { Id = 292, Name = "100 Miles Professional Championship of Britain", ColorHex = (string?)null, NationId = 8, DarkText = false },
            new { Id = 293, Name = "24 heures de Bordeaux", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 294, Name = "24 heures de Buffalo", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 295, Name = "24 heures de Verviers", ColorHex = (string?)null, NationId = 2, DarkText = false },
            new { Id = 296, Name = "24 heures du Palais des Arts Libereaux", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 297, Name = "Driedaagse Van Antwerpen", ColorHex = (string?)null, NationId = 2, DarkText = false },
            new { Id = 298, Name = "Dunlop Grand Prix", ColorHex = (string?)null, NationId = 8, DarkText = false },
            new { Id = 299, Name = "France-Championnat de fond", ColorHex = (string?)null, NationId = 3, DarkText = false },
            new { Id = 300, Name = "Milano-München", ColorHex = (string?)null, NationId = 7, DarkText = false },
            new { Id = 301, Name = "Six Days Memphis", ColorHex = (string?)null, NationId = 9, DarkText = false },
            new { Id = 302, Name = "Newzealandsk mester", ColorHex = "#000000", NationId = 39, DarkText = false },
            new { Id = 303, Name = "Newzealandsk mester i enkeltstart", ColorHex = "#000000", NationId = 39, DarkText = false }
        ];
    }
}